steps:
  - name: node
    entrypoint: npm
    args: ['ci']
  - name: node
    entrypoint: npm
    args: ['run', 'build']
artifacts:
  objects:
    location: 'gs://chart-components-bucket/'
    paths: ['dist/barchart.bundle.js']

